<%@ Page Language="C#" MasterPageFile="../MasterPages/AdminAddis.master" AutoEventWireup="true" CodeFile="FAQ.aspx.cs" Inherits="Admin_FAQ" Title="FAQ" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>
<TABLE><TBODY><TR><TD style="WIDTH: 621px"><SPAN style="FONT-SIZE: 16pt"><SPAN style="COLOR: #0000ff"><SPAN style="FONT-SIZE: 14pt; FONT-FAMILY: Tahoma">FAQ</SPAN><BR /></SPAN></SPAN>
<HR />
&nbsp; <asp:Label id="lblUser" runat="server" Text="Label" ForeColor="Blue" Font-Size="10pt" Font-Names="tahoma" Font-Bold="True"></asp:Label></TD></TR><TR><TD style="WIDTH: 621px" class="messagetext" vAlign=top><asp:Label id="lblMessage" runat="server" ForeColor="Red" Font-Size="8pt" Font-Bold="True" Width="295px"></asp:Label></TD></TR><TR><TD style="WIDTH: 621px; HEIGHT: 19px"><SPAN style="FONT-SIZE: 7pt; COLOR: #000099">Select Question or Create New: </SPAN></TD></TR><TR><TD style="WIDTH: 621px; HEIGHT: 21px" vAlign=top>&nbsp;<asp:DropDownList id="ddListOperation" runat="server" OnSelectedIndexChanged="ddListOperation_SelectedIndexChanged" AutoPostBack="True">   
     </asp:DropDownList></TD></TR><TR><TD>&nbsp; <asp:Label id="lblSta" runat="server" Text="Status:" ForeColor="#000099" Font-Size="7pt" Visible="False"></asp:Label> <asp:Label id="lblStatus" runat="server" Font-Size="8pt" Font-Bold="True" Width="53px" Visible="false"></asp:Label><BR /></TD></TR><TR><TD style="WIDTH: 621px; HEIGHT: 187px" vAlign=top><TABLE style="WIDTH: 618px"><TBODY><TR><TD style="WIDTH: 7px; HEIGHT: 6px" vAlign=top><asp:Label id="Label2" runat="server" Text="Question  : " ForeColor="#000099" Font-Size="7pt" Width="179px"></asp:Label> </TD></TR><TR><TD style="WIDTH: 7px; HEIGHT: 4px" vAlign=top><asp:TextBox id="txtQuestion" runat="server"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator1" runat="server" Width="174px" ValidationGroup="contactUs" ErrorMessage="Question  Required !" ControlToValidate="txtQuestion"></asp:RequiredFieldValidator></TD></TR><TR><TD style="WIDTH: 7px" vAlign=top><asp:Label id="Label3" runat="server" Text="Answer  :" ForeColor="#000099" Font-Size="7pt" Width="358px"></asp:Label></TD></TR><TR><TD style="WIDTH: 7px; HEIGHT: 49px" vAlign=top><asp:TextBox id="txtAnswer" runat="server" Width="362px" TextMode="MultiLine" Height="45px"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator2" runat="server" Width="174px" ValidationGroup="contactUs" ErrorMessage="Answer  Required !" ControlToValidate="txtAnswer"></asp:RequiredFieldValidator></TD></TR></TBODY></TABLE></TD></TR><TR><TD style="WIDTH: 621px; HEIGHT: 28px"><P class="main">Select one from the buttons below according to the actions you wish (and have the permissions) to perform. <BR /><BR /></P></TD></TR><TR><TD style="WIDTH: 621px"><asp:Button id="btnSave" onclick="btnSave_Click" runat="server" Text="Save" ValidationGroup="contactUs"></asp:Button>&nbsp;<asp:Button id="btnApprove" onclick="btnApprove_Click" runat="server" Text="Approve"></asp:Button><asp:Button id="btnDelete" onclick="btnDelete_Click" runat="server" Text="Delete"></asp:Button> <asp:Button id="btnReset" onclick="btnReset_Click" runat="server" Text="Reset"></asp:Button> </TD></TR></TBODY></TABLE>
</ContentTemplate>
    </asp:UpdatePanel>
    
</asp:Content>

